In [4]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [23]:
from urllib.error import HTTPError
import logging
import time
from html_table_parser import parser_functions as parser
import pandas as pd

def collect_sheet(code):
    try_cnt = 0
    try:
        URL = "http://comp.fnguide.com/SVO2/ASP/SVD_Finance.asp?pGB=1&gicode=" + code
        
        req = urlopen(URL)
        html = req.read()

        soup = BeautifulSoup(html, 'html.parser')

        # 조건 만족하는 태그 전체
        soup_table_all = soup.find_all("table")
        # 클래스 선택자로 정보 탐색
        soup.find(attrs={"us_table_ty1 h_fix zigbg_no"})
        soup_table = soup.find("table", attrs={"us_table_ty1 h_fix zigbg_no"})
        # html_table_parser 이용 Pandas DataFrame으로 표 형식 변경
        table = parser.make2d(soup_table)
        df = pd.DataFrame(table[1:], columns=table[0])
        
        return df
    
    except HTTPErro as e:
        if try_cnt>=3:
            logging.warning(e)
            return None
        else:
            time.sleep(3)
            collect_div(corp_code,try_cnt=+1)

In [25]:
collect_sheet("A005930").head()

,IFRS(연결),2017/12,2018/12,2019/12,2020/09,전년동기,전년동기(%)
0,매출액,"2,395,754","2,437,714","2,304,009","1,752,555","1,705,161",2.8
1,매출원가,"1,292,907","1,323,944","1,472,395","1,066,834","1,086,850",-1.8
2,매출총이익,"1,102,847","1,113,770","831,613","685,721","618,311",10.9
3,판매비와관리비계산에 참여한 계정 펼치기,"566,397","524,903","553,928","416,252","412,229",1.0
4,인건비,"67,972","64,514","64,226","51,701","49,271",4.9